FROM python:3.10-slim

WORKDIR /app

COPY . /app

RUN pip install --upgrade pip
RUN pip install flask python-telegram-bot facefusion

RUN mkdir -p static

EXPOSE 5000

CMD ["python", "app.py"]
